name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          if [[ "$REPO_NAME" == *.github.io ]]; then
            BASE_HREF="/"
          else
            BASE_HREF="/${REPO_NAME}/"
          fi

          npm run build -- --configuration production --base-href "$BASE_HREF"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/junior-frontend-developer-task/browser
          clean: true
